### ISSUE TITLE
Week 1 (January 2024)

### ISSUE THREAD

**Issue by TDT1401** [TDT1401/Study-English#1]
**Todo list** 

- [ ] learn IPA consonant

**Comment by TDT1401** [comment]
**Friday, January 5**

- [ ] Review unit 4: Likes and Dislikes
- [ ] review fruit vocabulary

**Comment by TDT1401** [comment]
**Sunday, January 7**

- [ ] review 12 one sound IPA vowel
- [ ] Do homework prepositions of time
- [ ] Review fruit vocabulary
